import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, BadgeCheck, CalendarDays, Check, Dumbbell, HeartHandshake, Instagram, MessageCircle, ShieldCheck } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { createBookingGateway } from './booking/create-gateway'
import { bookingErrorMessage } from './booking/errors'
import { slotLabel } from './booking/time'
import { identitySchema } from './booking/validation'
import type { BookingMode, PartnerAcademy, PlanCode, Reservation, ReservationInput, Slot } from './booking/types'
import { plans, resolvePlan } from './payments/catalog'
import logo from './assets/nutri-broow-logo-transparent.png'
import nutritionistPhoto from './assets/nutricionista-consulta.png'
import routinePhoto from './assets/surf-niteroi.jpg'
import goalsPhoto from './assets/benefit-metas.png'
import orientationPhoto from './assets/benefit-orientacao.png'
import routineBenefitPhoto from './assets/benefit-rotina.png'
import followUpPhoto from './assets/benefit-acompanhamento.png'
import './logo.css'
import './hero-photo.css'
import './routine-photo.css'

const gateway = createBookingGateway()
type FormValues = Omit<ReservationInput, 'slotId' | 'mode' | 'academyCode'>
const Button = ({ children, className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button className={`button ${className}`} {...props}>{children}</button>
const slotDayKey = (startsAt: string) => new Intl.DateTimeFormat('en-CA', { year: 'numeric', month: '2-digit', day: '2-digit', timeZone: 'America/Sao_Paulo' }).format(new Date(startsAt))
const slotDayLabel = (startsAt: string) => new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', timeZone: 'America/Sao_Paulo' }).format(new Date(startsAt))
const slotDayShortLabel = (startsAt: string) => new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit', timeZone: 'America/Sao_Paulo' }).format(new Date(startsAt))
const slotTimeLabel = (startsAt: string) => new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'America/Sao_Paulo' }).format(new Date(startsAt))
const slotWeekday = (startsAt: string) => new Intl.DateTimeFormat('en-US', { weekday: 'short', timeZone: 'America/Sao_Paulo' }).format(new Date(startsAt))
const isHiddenOnlineSlot = (slot: Slot) => slot.mode === 'online' && ((slotTimeLabel(slot.startsAt) === '12:00' && slotWeekday(slot.startsAt) !== 'Sat') || (slotTimeLabel(slot.startsAt) === '19:00' && slotWeekday(slot.startsAt) === 'Wed'))

export default function App() {
  const [partner, setPartner] = useState<PartnerAcademy | null>(null); const [partnerReady, setPartnerReady] = useState(false)
  const [mode, setMode] = useState<BookingMode>('online'); const [slots, setSlots] = useState<Slot[]>([]); const [selected, setSelected] = useState<Slot | null>(null); const [selectedDay, setSelectedDay] = useState<string | null>(null)
  const [stage, setStage] = useState<'plan'|'slots'|'form'|'confirmation'>('plan'); const [reservation, setReservation] = useState<Reservation | null>(null); const [selectedPlan, setSelectedPlan] = useState<PlanCode | null>(null); const [error, setError] = useState('')
  const code = useMemo(() => new URLSearchParams(window.location.search).get('unidade'), [])
  const paymentReservationId = useMemo(() => { const search = new URLSearchParams(window.location.search); return search.get('pagamento') === 'success' ? search.get('reserva') : null }, [])
  const [paymentReturnError, setPaymentReturnError] = useState('')
  const form = useForm<FormValues>({ resolver: zodResolver(identitySchema) as never, defaultValues: { name: '', email: '', phone: '', birthDate: '', age: undefined, consentBooking: false, consentSharing: false } })
  const loadSlots = async (next: BookingMode) => { setMode(next); setSelected(null); setSelectedDay(null); setError(''); try { const availableSlots = (await gateway.getSlots(next, partner?.code)).filter(slot => !isHiddenOnlineSlot(slot)); setSlots(availableSlots); setSelectedDay(availableSlots[0] ? slotDayKey(availableSlots[0].startsAt) : null) } catch (e) { setError(bookingErrorMessage((e as { code?: string }).code || 'service_unavailable')) } }
  useEffect(() => { gateway.getPartner(code).then(setPartner).finally(() => setPartnerReady(true)) }, [code])
  // The initial load deliberately runs once after partner resolution; user actions invoke loadSlots afterwards.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (partnerReady && selectedPlan) void loadSlots('online') }, [partnerReady, selectedPlan])
  useEffect(() => {
    if (!paymentReservationId) return
    let cancelled = false; let attempts = 0; let timer: number | undefined
    const waitForConfirmation = async () => {
      try {
        const confirmation = await gateway.getPaymentConfirmation(paymentReservationId)
        if (confirmation.status === 'confirmed') { window.location.assign(confirmation.whatsappUrl); return }
      } catch { /* The webhook may still be processing; retry below. */ }
      attempts += 1
      if (attempts < 12 && !cancelled) timer = window.setTimeout(() => void waitForConfirmation(), 2000)
      else if (!cancelled) setPaymentReturnError('Seu pagamento está sendo confirmado. Atualize esta página em instantes para continuar pelo WhatsApp.')
    }
    void waitForConfirmation()
    return () => { cancelled = true; if (timer) window.clearTimeout(timer) }
  }, [paymentReservationId])
  const reserve = async (values: FormValues) => { if (!selected) return; try { setReservation(await gateway.reserve({ ...values, mode, slotId: selected.id, academyCode: partner?.code })); setStage('confirmation') } catch (e) { setError(bookingErrorMessage((e as { code?: string }).code || 'service_unavailable')) } }
  const scroll = () => document.getElementById('agendamento')?.scrollIntoView({ behavior: 'smooth' })
  const availableDays = useMemo(() => Array.from(new Map(slots.map(slot => [slotDayKey(slot.startsAt), slot])).values()), [slots])
  const visibleSlots = selectedDay ? slots.filter(slot => slotDayKey(slot.startsAt) === selectedDay) : []
  if (paymentReservationId) return <main><section className="booking"><div><span className="eyebrow orange booking-eyebrow-large">PAGAMENTO APROVADO</span><h1>Estamos preparando sua confirmação.</h1><p>{paymentReturnError || 'Você será encaminhado para o WhatsApp do nutricionista em instantes.'}</p></div></section></main>
  return <><header><a className="brand logo-link" href="#inicio" aria-label="Nutri Broow — início"><img src={logo} alt="Logo Nutri Broow" /></a><nav><a href="#como">Como funciona</a><a href="#oferta">Acompanhamento</a><Button onClick={scroll}>Agendar <ArrowRight size={16}/></Button></nav></header><main>
    <section id="inicio" className="hero"><div><h1>Sua rotina não precisa caber num plano. <em>O plano cabe nela.</em></h1><p>Um acompanhamento nutricional humano, individual e sustentável para ganhar clareza e constância.</p><Button onClick={scroll}>Quero agendar <ArrowRight size={18}/></Button></div><figure className="hero-art"><img src={nutritionistPhoto} alt="Nutricionista em consulta no consultório" /></figure></section>
    <section className="dark"><span className="eyebrow orange challenge-eyebrow-large">SEM FÓRMULA PRONTA</span><h2 className="challenge-heading">Você não precisa de mais uma regra impossível, mas...</h2><div className="cards">{['se tem dificuldade em manter a consistência;','se não consegue organizar a rotina alimentar;','se reclama de pouca energia para cumprir a rotina do dia-dia;','e se acha difícil seguir um planejamento alimentar.'].map((x,i)=><article key={x}><b>0{i+1}</b><p className="challenge-card-copy">{x}</p></article>)}</div></section>
    <section className="benefits-section"><span className="eyebrow orange benefits-eyebrow benefits-eyebrow-large">AQUI VOCÊ ENCONTRA!</span><h2 className="benefits-heading">Mais clareza para decidir.<br/><em>Mais leveza para continuar.</em></h2><div className="cards benefits">{[[CalendarDays,'Metas reais',goalsPhoto],[HeartHandshake,'Orientação individual',orientationPhoto],[Dumbbell,'Rotina possível',routineBenefitPhoto],[ShieldCheck,'Acompanhamento',followUpPhoto]].map(([I,t,image])=>{const Icon=I as typeof CalendarDays; const style=image?{'--benefit-image':`url(${image})`} as React.CSSProperties:undefined; return <article className={`${image?'benefit-card-photo':''}${t==='Orientação individual'?' benefit-card-orientation':''}`} style={style} key={String(t)}><Icon/><h3>{String(t)}</h3></article>})}</div><figure className="routine-photo"><img src={routinePhoto} alt="Pessoa surfando uma onda" /></figure></section>
    <section id="como" className="dark"><span className="eyebrow orange journey-eyebrow-large">UMA JORNADA DIRETA</span><h2 className="journey-heading">Do primeiro passo à confirmação.</h2><ol className="journey-list">{[['Escolha o tipo de atendimento','Online ou presencial, quando disponível pela academia parceira.'],['Selecione o melhor horário','Veja apenas horários livres e escolha o que encaixa na rotina.'],['Preencha seus dados','Nome, e-mail, telefone, idade e nascimento para identificar a reserva.'],['Confirme a reserva temporária','O horário fica reservado por 15 minutos.'],['Finalize o pagamento','Pix ou cartão via Mercado Pago para confirmar a consulta.'],['Fale com o nutricionista','Após o pagamento, você será direcionado ao WhatsApp com os detalhes do agendamento.']].map(([title,detail],i)=><li key={title}><b>0{i+1}</b><div><h3>{title}</h3><p>{detail}</p></div></li>)}</ol></section>
    <section id="oferta" className="offer"><div><span className="eyebrow orange offer-eyebrow-large">ACOMPANHAMENTO NUTRI BROOW</span><h2 className="offer-heading">Três meses para construir constância.</h2><p>Consulta inicial de 45 minutos, acompanhamento individual e ajustes possíveis. Valores e condições serão conversados com transparência.</p></div><aside><Check/> <span>Estratégias práticas para a sua rotina</span><Check/> Acompanhamento individual<Check/> Plano adaptado</aside></section>
    <section id="agendamento" className="booking"><div><span className="eyebrow orange booking-eyebrow-large">SEU MOMENTO</span><h2 className="booking-heading">Vamos encontrar um horário?</h2><p>Escolha o plano, defina como quer ser atendido e selecione o melhor horário para sua rotina.</p>{partner ? <p className="partner"><BadgeCheck/> Parceiro <b>{partner.name}</b> · desconto aplicado</p> : <p className="notice">Atendimento presencial disponível somente via QR de academia parceira.</p>}</div><div className="wizard" aria-live="polite">
      {stage==='plan' && <div className="plan-step"><span className="step-label">Etapa 1 de 3</span><h3 className="plan-step-title">Agende sua consulta</h3><p>Escolha o plano que combina com seu momento.</p><div className="cards benefits">{plans.map(plan=>{const resolved=resolvePlan(plan.code,partner?.code);const isPartnerPlan=Boolean(partner&&plan.code==='consulta_trimensal');return <button className={`slot plan-card${isPartnerPlan?' partner-plan':''}`} key={plan.code} onClick={()=>{setSelectedPlan(plan.code);setStage('slots')}}>{isPartnerPlan&&<span className="plan-badge">Exclusivo para parceiros</span>}<b>{resolved.title}</b><span className="plan-price">R$ {(resolved.unitAmountCents/100).toFixed(2).replace('.',',')}</span><small>{resolved.durationLabel}</small><span className="choose-plan">Escolher este plano <ArrowRight size={16}/></span></button>})}</div></div>}
      {stage==='slots' && <><button type="button" className="back" onClick={()=>setStage('plan')}><ArrowLeft size={16}/> Alterar plano</button><h3>2. Modalidade e horário</h3><div className="mode"><Button className={mode==='online'?'':'secondary'} onClick={()=>void loadSlots('online')}>Online</Button><Button disabled={!partner} className={mode==='presencial'?'':'secondary'} onClick={()=>void loadSlots('presencial')}>Presencial</Button></div>{error?<><p className="error">{error}</p><Button onClick={()=>void loadSlots(mode)}>Tentar novamente</Button></>:slots.length?<><div className="days" aria-label="Dias disponíveis">{availableDays.map(day=><button type="button" className={selectedDay===slotDayKey(day.startsAt)?'day selected':'day'} aria-pressed={selectedDay===slotDayKey(day.startsAt)} aria-label={slotDayLabel(day.startsAt)} onClick={()=>{setSelectedDay(slotDayKey(day.startsAt));setSelected(null)}} key={slotDayKey(day.startsAt)}>{slotDayShortLabel(day.startsAt)}</button>)}</div><div className="slots" aria-label="Horários disponíveis">{visibleSlots.map(s=><button className={selected?.id===s.id?'slot selected':'slot'} aria-label={slotLabel(s.startsAt)} onClick={()=>setSelected(s)} key={s.id}><span className="slot-time">{slotTimeLabel(s.startsAt)}</span></button>)}</div></>:<p>Carregando ou nenhum horário disponível.</p>}<Button disabled={!selected} onClick={()=>setStage('form')}>Continuar <ArrowRight size={16}/></Button></>}
      {stage==='form' && <form onSubmit={form.handleSubmit((values) => void reserve(values))}><button type="button" className="back" onClick={()=>setStage('slots')}><ArrowLeft size={16}/> Alterar horário</button><h3>3. Seus dados</h3><label>Nome completo<input {...form.register('name')}/>{form.formState.errors.name&&<small className="error">{form.formState.errors.name.message}</small>}</label><label>E-mail<input type="email" {...form.register('email')}/>{form.formState.errors.email&&<small className="error">{form.formState.errors.email.message}</small>}</label><label>Telefone<input {...form.register('phone')}/>{form.formState.errors.phone&&<small className="error">{form.formState.errors.phone.message}</small>}</label><label>Data de nascimento<input type="date" {...form.register('birthDate')}/>{form.formState.errors.birthDate&&<small className="error">{form.formState.errors.birthDate.message}</small>}</label><label>Idade<input type="number" min="1" max="120" {...form.register('age')}/>{form.formState.errors.age&&<small className="error">{form.formState.errors.age.message}</small>}</label><label className="check"><input type="checkbox" {...form.register('consentBooking')}/> Li a <a href="#privacidade">Política de Privacidade</a> e concordo com a reserva temporária.</label>{form.formState.errors.consentBooking&&<small className="error">{form.formState.errors.consentBooking.message}</small>}<label className="check"><input type="checkbox" {...form.register('consentSharing')}/> Concordo com o compartilhamento operacional necessário com a academia parceira.</label>{form.formState.errors.consentSharing&&<small className="error">{form.formState.errors.consentSharing.message}</small>}{error&&<p className="error">{error}</p>}<Button type="submit">Criar reserva <ArrowRight size={16}/></Button></form>}
      {stage==='confirmation' && reservation && selectedPlan && <><span className="success"><Check/> Reserva temporária criada por 15 minutos</span><h3>Finalize seu pagamento</h3><p><b>{resolvePlan(selectedPlan,partner?.code).title}</b> · R$ {(resolvePlan(selectedPlan,partner?.code).unitAmountCents/100).toFixed(2).replace('.',',')}</p><p>Pix ou cartão em até 3x; juros definidos pelo Mercado Pago.</p><p>Após a confirmação, você será direcionado ao WhatsApp do nutricionista com os dados do agendamento.</p><Button onClick={()=>void gateway.createCheckout({reservationId:reservation.id,planCode:selectedPlan}).then(session=>window.location.assign(session.checkoutUrl)).catch(e=>setError(bookingErrorMessage((e as {code?:string}).code||'service_unavailable')))}>Ir para pagamento <ArrowRight size={16}/></Button>{error&&<p className="error">{error}</p>}<small>A reserva temporária não confirma definitivamente a consulta.</small></>}
    </div></section>
    <section id="privacidade" className="privacy"><ShieldCheck/><div><span className="eyebrow orange">PRIVACIDADE E LGPD</span><h2>Privacidade e proteção de dados</h2><p className="privacy-copy">Usamos seus dados de contato e reserva para agendar e confirmar sua consulta, processar o pagamento e enviar comunicações. O compartilhamento é limitado aos serviços necessários — Supabase, Mercado Pago, Google Calendar e Resend — e não armazenamos dados de cartão. Dados de reserva e atendimento podem ser mantidos por até 5 anos após a última consulta, ou pelo prazo legal aplicável.</p><p className="privacy-rights">Para acessar, corrigir, atualizar ou eliminar seus dados, envie uma <a href="mailto:agendamento@nutribroow.com?subject=Solicita%C3%A7%C3%A3o%20LGPD">Solicitação LGPD</a>.</p></div></section>
  </main><footer><span className="brand">Nutri <i>Broow</i></span><a className="privacy-link" href="#privacidade">Privacidade e LGPD</a><span className="social-links"><a aria-label="Instagram" target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/nutribroow/"><Instagram size={20}/></a><a aria-label="WhatsApp" target="_blank" rel="noopener noreferrer" href="https://wa.me/5521980966678"><MessageCircle size={20}/></a></span></footer></>
}
