create extension if not exists pgcrypto;
create table public.partner_academies (id uuid primary key default gen_random_uuid(), code text not null unique check (code = lower(trim(code))), name text not null, address text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.availability_slots (id uuid primary key default gen_random_uuid(), mode text not null check (mode in ('online','presencial')), academy_id uuid references public.partner_academies(id), starts_at timestamptz not null, ends_at timestamptz not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (ends_at = starts_at + interval '45 minutes'), check ((mode='online' and academy_id is null) or (mode='presencial' and academy_id is not null)));
create table public.patients (id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 3 and 120), email text not null, phone text not null check (phone ~ '^\d{10,11}$'), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reservations (id uuid primary key default gen_random_uuid(), slot_id uuid not null references public.availability_slots(id), patient_id uuid not null references public.patients(id), academy_id uuid references public.partner_academies(id), mode text not null check (mode in ('online','presencial')), status text not null check (status in ('temporary','expired','cancelled')) default 'temporary', expires_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index reservations_one_live_slot on public.reservations(slot_id) where status='temporary';
alter table public.partner_academies enable row level security; alter table public.availability_slots enable row level security; alter table public.patients enable row level security; alter table public.reservations enable row level security;
create or replace function public.create_temporary_reservation(p_slot uuid,p_name text,p_email text,p_phone text,p_academy uuid default null) returns public.reservations language plpgsql security definer set search_path=public as $$ declare s availability_slots; pat uuid; res reservations; begin select * into s from availability_slots where id=p_slot and active for update; if not found or s.starts_at < now()+interval '24 hours' or s.starts_at > now()+interval '60 days' then raise exception 'slot_unavailable'; end if; update reservations set status='expired' where slot_id=p_slot and status='temporary' and expires_at<=now(); if exists(select 1 from reservations where slot_id=p_slot and status='temporary' and expires_at>now()) then raise exception 'slot_unavailable'; end if; if s.mode='presencial' and (p_academy is null or p_academy<>s.academy_id) then raise exception 'slot_unavailable'; end if; insert into patients(name,email,phone) values(trim(p_name),lower(trim(p_email)),p_phone) returning id into pat; insert into reservations(slot_id,patient_id,academy_id,mode,status,expires_at) values(p_slot,pat,coalesce(p_academy,s.academy_id),s.mode,'temporary',now()+interval '15 minutes') returning * into res; return res; exception when unique_violation then raise exception 'slot_unavailable'; end $$;
revoke all on all tables in schema public from anon, authenticated; revoke all on function public.create_temporary_reservation(uuid,text,text,text,uuid) from public;
